# Generated by Django 4.2 on 2024-04-17 17:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_platform', '0004_remove_item_image_item_area_item_camera_monitoring_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_rented',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='rental_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='rented_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rentals', to=settings.AUTH_USER_MODEL),
        ),
    ]
