# Generated by Django 4.2 on 2024-04-30 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_platform', '0006_item_latitude_item_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=30, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=30, max_digits=30, null=True),
        ),
    ]
